export const types = {
    // User types
    SET_AUTHENTICATED: 'SET_AUTHENTICATED',
    SET_UNAUTHENTICATED: 'SET_UNAUTHENTICATED',
    SET_USER: 'SET_USER',
    SET_METRICS: 'SET_METRICS',
    LOADING_USER: 'LOADING_USER',
    EDIT_METRIC: 'EDIT_METRIC',
    EDIT_ACC: 'EDIT_ACC',
    // UI types
    SET_ERRORS: 'SET_ERRORS',
    LOADING_UI: 'LOADING_UI',
    CLEAR_ERRORS: 'CLEAR_ERRORS',
}